version: "3.7"

services:
  api:
    image: api-rest:1.0
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/postgres
      PORT: 80

  db:
    image: db:1.0
    ports:
      - "35432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    volumes:
      - ./var/lib/postgresql/data/
